version: "3.9"
services:
    # Database instance
    db:
      image: mcr.microsoft.com/azure-sql-edge:latest
      container_name: db
      volumes:
        - events_db:/var/opt/mssql
      ports:
        - 1433:1433
      environment:
        - ACCEPT_EULA=1
        - SA_PASSWORD=Vyshnu@2000
volumes:
    events_db: